<?php

namespace APP\AnswersBundle\Entity;

/**
 * MostSearchedAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MostSearchedAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
